.github/workflows/artifacts.yaml, v1.10/Dockerfile, v1.10/entrypoint.sh, v1.10/fluent.conf, v1.10/healthy.sh, v1.11/Dockerfile, v1.11/entrypoint.sh, v1.11/fluent.conf, v1.11/healthy.sh, v1.12/Dockerfile, v1.12/entrypoint.sh, v1.12/fluent.conf, v1.12/healthy.sh, v1.13/Dockerfile, v1.13/entrypoint.sh, v1.13/fluent.conf, v1.13/healthy.sh, v1.14/Dockerfile, v1.14/entrypoint.sh, v1.14/fluent.conf, v1.14/healthy.sh, v1.7/Dockerfile, v1.7/entrypoint.sh, v1.7/fluent.conf, v1.7/healthy.sh, v1.9/Dockerfile, v1.9/entrypoint.sh, v1.9/fluent.conf, v1.9/healthy.sh
Signed-off-by: Mark Sagi-Kazar <mark.sagikazar@gmail.com>
=> add currently supported images

v1.12/Dockerfile, v1.13/Dockerfile, v1.14/Dockerfile
Signed-off-by: Mark Sagi-Kazar <mark.sagikazar@gmail.com>
=> pin patch versions

v1.15-minimal-dev/Dockerfile, v1.15-minimal-dev/entrypoint.sh, v1.15-minimal-dev/fluent.conf, v1.15-minimal-dev/healthy.sh
Upgrade alpine (3.14 -> 3.17), ruby (2.7 -> 3.1) and all the components. Also pin all components for reproducibility.
=> Upgrade alpine, ruby and all the deps

v1.15-staging/Dockerfile
=> deps: pin activesupport on the latest version on 6.x

.github/workflows/artifacts.yaml
=> fix: do not create smart tags as they conflict with each other

v1.15-staging/Dockerfile
=> deps: upgrade elastic plugin to avoid dependency conflict with faraday

.github/workflows/ci.yaml, v1.15-ruby3/Dockerfile, v1.15-ruby3/entrypoint.sh, v1.15-ruby3/fluent.conf, v1.15-ruby3/healthy.sh
- fork: copy v1.15-staging as v1.15-ruby3
- ci: introduce ci step that is faster (single arch) and runs only for PRs
=> Introduce a ruby3 based image and optimize PR builds

v1.15-ruby3/Dockerfile, v1.15-staging/Dockerfile
=> chore: downgrade async libs for compatibility with fluentd

v1.15-ruby3/Dockerfile, v1.15-staging/Dockerfile
Bump opensearch plugin release to latest. Fixes #50 .
=> bump opensearch plugin to resolve conflict

v1.15-ruby3/Dockerfile, v1.15-staging/Dockerfile
Fixes https://github.com/kube-logging/logging-operator/issues/1361
=> deps: replace fluent-plugin-oss gem by fluent-plugin-aliyun-oss

.github/workflows/ci.yaml, v1.16/Dockerfile
=> feat: set oci labels for docker image in ci job

v1.16/Dockerfile
=> base image and uri upgrade

v1.16/Dockerfile
Signed-off-by: Szilard Parrag <szilard.parrag@axoflow.com>
=> chore(pkg): force specific libcrypto version

v1.16/Dockerfile
=> fix: rebuild base gems for native extensions

v1.16-4.8/Dockerfile, v1.16/Dockerfile
fixes https://github.com/kube-logging/logging-operator/issues/1716
=> fix syslog plugin ruby3 compatibility

v1.16-4.10/filters/Gemfile.lock, v1.16-4.10/outputs/Gemfile.lock, v1.16-4.8/filters/Gemfile.lock, v1.16-4.8/outputs/Gemfile.lock, v1.16-4.9/filters/Gemfile.lock, v1.16-4.9/outputs/Gemfile.lock
=> Dep upgrades

v1.16-4.10/Dockerfile, v1.16-4.8/Dockerfile, v1.16-4.9/Dockerfile
=> chore: webrick and protobuf upgrade in the base image

.github/workflows/artifacts.yaml, renovate.json
- **trivy: use up-to-date action**
- **renovate: separate pr per folder**
=> Trivy action upgrade

.github/workflows/artifacts.yaml
=> trivy: fix java db location

renovate.json
=> Create separate pr per path

v1.17-5.0/outputs/Gemfile, v1.17-5.0/outputs/Gemfile.lock
=> Remove sumologic output from v5

renovate.json
=> limit currently released versions to patch bumps only

renovate.json
=> limit renovate updates for existing version to security patches only
